# =====================================
# Shared SSL parameters
# =====================================

# ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

# Enable 0-RTT
ssl_early_data on;
ssl_session_cache shared:SSL:10m; # SSL session caching for performance

# HSTS (uncomment when ready for production)
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
